apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: abisga/api_node:1.0
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: node-data-volume
          mountPath: /app/data  # Ruta en la que se montará el volumen
      volumes:
      - name: node-data-volume
        persistentVolumeClaim:
          claimName: node-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30000
  type: NodePort
   # Cambiado a NodePort para exponer en Minikube
